# Generated by Django 4.1.2 on 2022-10-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='postimages'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
